project:
  type: book

book:
  title: "quarto"
  author: "Jane Doe"
  date: "2/20/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



